### ISSUE TITLE
Cypress upgrade tests failing

### ISSUE THREAD

**Issue by liza-mae** [elastic/elastic-stack-testing#1075]
The cloud upgrade tests for rules are failing, here are a few: 

- "after all" hook for "Displays the correct timeline details on the timelines page".Import timeline after upgrade "after all" hook for "Displays the correct timeline details on the timelines page"

![Import timeline after upgrade -- Displays the correct timeline details on the timelines page -- after all hook (failed)](https://user-images.githubusercontent.com/23424008/141203524-438ccd8b-5de5-4467-be09-af0d2f2a0e60.png)

- "before all" hook for "Displays the correct timeline details on the timelines page".Import timeline after upgrade "before all" hook for "Displays the correct timeline details on the timelines page" 

![Import timeline after upgrade -- Displays the correct timeline details on the timelines page -- before all hook (failed)](https://user-images.githubusercontent.com/23424008/141203492-392a17bf-b606-46af-bba8-68d5804c69a9.png)

- Has the expected alerts number.After an upgrade, the custom query rule Has the expected alerts number

![After an upgrade, the custom query rule -- Has the expected alerts number (failed)](https://user-images.githubusercontent.com/23424008/141203467-67d367aa-45f5-47c4-9d3c-e0e52a0dfcd5.png)

- Displays the correct timeline details inside the query tab.Import timeline after upgrade Displays the correct timeline details inside the query tab 

```
Timed out retrying after 60050ms: `cy.click()` failed because this element:  `<button class="euiLink euiLink--primary" type="button" data-test-subj="title-98d78010-41a2-11ec-9e8e-070444b08be5">...</button>`  is being covered by another element:  `<div class="euiFlexGroup euiFlexGroup--alignItemsCenter euiFlexGroup--directionRow euiFlexGroup--responsive" aria-label="You are in group 1">...</div>`  Fix this problem, or use {force: true} to disable error checking.  https://on.cypress.io/element-cannot-be-interacted-with
```

- Displays the alert details.After an upgrade, the custom query rule Displays the alert details 
```
Timed out retrying after 60000ms: Expected to find content: 'Custom query rule for upgrade' within the element: [ <div.euiDataGridRowCell>, 8 more... ]
```

- Displays the correct timeline details inside the pinned tab.Import timeline after upgrade Displays the correct timeline details inside the pinned tab 

```
Timed out retrying after 60000ms: expected '<div>' to contain 'Oct 7, 2021 @ 11:14:10.888'
```

https://internal-ci.elastic.co/view/Stack%20Tests/job/elastic+estf-cloud-upgrade-tests/lastCompletedBuild/testReport/

**Comment by MadameSheema** [comment]
Thanks @liza-mae those issues are legitimate bugs that are being/going to be addressed for this release.

**Comment by liza-mae** [comment]
Thanks @MadameSheema is it possible to link the PR tickets to this one, so we know when it is fixed and get a clear in CI?

**Comment by MadameSheema** [comment]
@liza-mae can you please confirm if this is still an issue? Thanks :)

**Comment by liza-mae** [comment]
@MadameSheema the tests are still failing, not sure yet if they are the same failures as mentioned originally, you can find the latest report here: https://internal-ci.elastic.co/view/Stack%20Tests/job/elastic+estf-cloud-upgrade-tests/162/testReport/

**Comment by MadameSheema** [comment]
Thanks @liza-mae!! I'll take a look as soon as I can.

**Comment by MadameSheema** [comment]
@liza-mae can you please confirm the upgrade path where the test is failing?

The current failure is different from the original one and I think it is a legitimate issue we need to fix. At least see this happening when it is an upgrade happening from 7.17 to 8.0, thanks!

**Comment by liza-mae** [comment]
Hi @MadameSheema all the paths are failing, so you can try one and see if it fixes the report above has the screenshots to compare if it is a similar failure.

**Comment by liza-mae** [comment]
@MadameSheema yes will check it, thanks for the fix.

**Comment by liza-mae** [comment]
@MadameSheema the original failures still exist, on latest runs. 
 
https://internal-ci.elastic.co/view/Stack%20Tests/job/elastic+estf-cloud-upgrade-tests/lastCompletedBuild/

**Comment by MadameSheema** [comment]
@liza-mae can you please confirm if the branch used was main or a different one? Thanks :)

**Comment by liza-mae** [comment]
@MadameSheema it was 7.17

**Comment by MadameSheema** [comment]
This PR https://github.com/elastic/kibana/pull/124980 should fix the issue.

**Comment by liza-mae** [comment]
Currently working to get these tests fixed, first iteration of 7.17 from PR: https://github.com/elastic/kibana/pull/127363 has reduced the failures from 50+ https://internal-ci.elastic.co/view/Stack%20Tests/job/elastic+estf-cloud-upgrade-tests/183/testReport/ to about 19 https://internal-ci.elastic.co/view/Stack%20Tests/job/elastic+estf-cloud-upgrade-tests/186/testReport/, it appears the screen takes time to load so these might just be flaky tests - investigating.  First iteration of 8.x is also pending: https://github.com/elastic/kibana/pull/127403

**Comment by liza-mae** [comment]
Currently the cypress security solution tests are blocked from running in CI on branch 8.x with the following error:
```
16:16:53 [2022-03-16 22:16:53] [INFO]  -> Running upgrade security solution tests, run 1 of 1 
16:16:53  debg KIBANA_CI_STATS_CONFIG environment variable not found, disabling CiStatsReporter
16:16:56  debg Loading config file from "/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest2j/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/x-pack/test/security_solution_cypress/upgrade_config.ts"
16:16:56  debg Loading config file from "/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest2j/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/test/common/config.js"
16:16:57 ERROR ValidationError: "servers.elasticsearch.auth" must be a string
16:16:57 [2022-03-16 22:16:57] [ERROR] Upgrade Security Solution Tests failed! 
16:16:57 
16:16:57 > Task :kibana:run_kibana_tests FAILED
```
This is coming from the FTR config validation and I don't see the error when I run the cypress locally, it is unclear to me the difference that would cause this error in CI environment but not local. 

In any case we have attempted to solve this issue before here: elastic/kibana#105095 but I believe this ended up being reverted by the security solutions team at one point.

**Comment by liza-mae** [comment]
Closing this issue as we have fixed a lot of test failures, I will open separate ones on failures in CI.
