### ISSUE TITLE
Logs upgrade tests broken on 8.5.2+

### ISSUE THREAD

**Issue by liza-mae** [elastic/elastic-stack-testing#1317]
This PR: https://github.com/elastic/kibana/pull/145130 appears to be causing new failures in the upgrade testing on cloud for 8.5.2 

Test Reports: https://internal-ci.elastic.co/view/Stack%20Tests/job/elastic+estf-cloud-upgrade-snapshot-tests+8.5/lastCompletedBuild/testReport/

cc: @bhavyarm

**Comment by bhavyarm** [comment]
@liza-mae yeah not sure why. Taking a look at this. Thanks!

**Comment by bhavyarm** [comment]
Had to revert the fix because of last 1 year missing bug in 8.5.2. This bug is fixed in 8.6.0/main - https://github.com/elastic/kibana/pull/146069

**Comment by bhavyarm** [comment]
I will wait for the test run on 8.5.x and close this out. PR is merged - https://github.com/elastic/kibana/pull/146069

**Comment by bhavyarm** [comment]
This works fine
