### ISSUE TITLE
Run each product's monitoring parity tests concurrently?

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-stack-testing#199]
Currently we have Monitoring parity tests for Elasticsearch and Kibana. The entrypoint for each of these tests is a separate playbook:
* Elasticsearch: https://github.com/elastic/elastic-stack-testing/tree/master/playbooks/monitoring/elasticsearch, and
* Kibana: https://github.com/elastic/elastic-stack-testing/tree/master/playbooks/monitoring/kibana. 

These playbooks are run sequentially. The sequence is set in this "meta" playbook, which is the entry point for all Monitoring parity tests, here: 

https://github.com/elastic/elastic-stack-testing/blob/55fac8dad53c5ff5978c8420f9c4b2fcfd99a0ea/playbooks/monitoring/docs_parity.yml#L19-L21

This means that if the Kibana parity tests fail, the Elasticsearch ones don't even get to run.

Is there some way to make these run concurrently instead?

Note that this problem will be exacerbated once we add tests for Logstash as well.

@liza-mae Thoughts?

**Comment by liza-mae** [comment]
@ycombinator some ideas: running tasks async in Ansible or create a multi-job in Jenkins.

**Comment by ycombinator** [comment]
Thanks @liza-mae. I looked into Ansible async tasks. I changed `playbooks/monitoring/docs_parity.yml` like so:

```
   tasks:
   - include: kibana/docs_parity.yml
+    async: 1000
+
   - include: elasticsearch/docs_parity.yml
+    async: 1000
+
```

From running the playbook it appears that the included Kibana tasks and Elasticsearch tasks run one after the other, not asynchronously.

What am I missing?

**Comment by cachedout** [comment]
Hi @ycombinator. Ansible does not support using the `async` keyword in at the include level.

To do this in Ansible I believe you need to apply the keyword directly to tasks which are actually specified in `kibana/docs_parity.yml` and `elasticsearch/docs_parity.yml`.

**Comment by liza-mae** [comment]
@ycombinator Mike is correct, you can't apply the async to the include, since you have two Ansible playbooks you can drive the execution in parallel through scripting, like Python.  Also since you are running these on one VM you would need to change the ports for Elasticsearch so they don't conflict.  Another option is to separate them into multiple jobs in CI.

**Comment by ycombinator** [comment]
Thanks @cachedout and @liza-mae. One added benefit of separating into multiple jobs in CI would be that we'd get a nicer breakdown (by branch + product) in the Jenkins UI + email notifications. That, in turn, would make for a better UX for debugging the failures IMO.

@liza-mae What would be involved in splitting up the current setup for Monitoring parity tests into multiple CI jobs, one per product? If you can give me general directions I can make the necessary PRs/issues to make this change.

**Comment by liza-mae** [comment]
@ycombinator for sure we have some examples in ESTF already, can you check out the details of job called: elastic+estf-kibana+master-snapshot-tests?

**Comment by ycombinator** [comment]
Awesome, thanks so much @liza-mae. I can take it from here!

**Comment by ycombinator** [comment]
Hi @liza-mae, I looked into that job you pointed me to and came up with the following set of changes for running child jobs per product for the ESTF Monitoring tests. Please let me know if I'm on the right general track or if I'm way off. I'm also happy to hear suggestions on how to do any of this better or in a more idiomatic fashion.

Here's what I'm thinking of changing:

1. I'd change this line:

   https://github.com/elastic/elastic-stack-testing/blob/6bc68234b1cba8ad82476f582bcf02d38b4046f7/playbooks/monitoring/buildenv.sh#L18

   to something like:

   ```
   export AIT_ANSIBLE_PLAYBOOK=monitoring/${AIT_STACK_PRODUCT}/docs_parity
   ```

   where `AIT_STACK_PRODUCT` would be an environment variable like `elasticsearch`, `kibana`, etc.

2. I'd make a similar change to this line:

   https://github.com/elastic/elastic-stack-testing/blob/6bc68234b1cba8ad82476f582bcf02d38b4046f7/playbooks/monitoring/ci/jenkins_monitoring.sh#L12

3. Since I'd be running the product playbooks directly, instead of going through the single "main" playbook, https://github.com/elastic/elastic-stack-testing/blob/master/playbooks/monitoring/docs_parity.yml, I might have tweak each product's playbook with tasks from the main playbook to get them to run correctly.

4. Then, over on the infra side, I'd edit https://github.com/elastic/infra/blob/master/ci/jjb/internal-ci/globals/templates/elastic+estf-monitoring/monitoring-tests.yml to make it look more like https://github.com/elastic/infra/blob/master/ci/jjb/internal-ci/globals/templates/elastic%2Bestf-kibana/snapshot-tests.yml. Specifically:

   1. I'd change the builder to be `multijob` with one `project` per product under it.

   2. I'd define each product's project in the same file with its own template. Each product's project template will be mostly the same except for the `parameters` section, which would look something like this:

   ```
   parameters:
     - string:
         name: AIT_STACK_PRODUCT
         default: "elasticsearch"
   ```
       
What do you think?

**Comment by liza-mae** [comment]
@ycombinator this looks like a great start !  It looks like it should work :)

**Comment by ycombinator** [comment]
@liza-mae @cachedout I've created 2 PRs to implement the changes I mentioned in my previous comment:

* For steps 1 - 3: https://github.com/elastic/elastic-stack-testing/pull/217
* For step 4: https://github.com/elastic/infra/pull/11478

Both PRs would need to be merged at about the same time.

**Comment by cachedout** [comment]
@ycombinator That approach seems totally reasonable to me. Let's see what @liza-mae thinks.

**Comment by liza-mae** [comment]
Looks great to me @ycombinator !
