### ISSUE TITLE
Add ML tests to ESTF cloud provisioning and Jenkins jobs

### ISSUE THREAD

**Issue by liza-mae** [elastic/elastic-stack-testing#21]
Add ML tests to cloud provisioning and jenkins ci. Reference: #18

- [ ] Cloud provisioning
- [ ] Jenkins CI

**Comment by dolaru** [comment]
@liza-mae when you say `add ML tests` what tests are we talking about? I'd love to get a better idea of your expectations and figure out how i can help.

**Comment by liza-mae** [comment]
Hi @dolaru This initiative is for cross-stack QA to run tests from each of the product teams against cloud.  Which tests are run is up to the product teams to decide and those tests are maintained in the product teams repo.  The common part or what plan to standardize is the provisioning and I have also created Jenkins jobs.  The information I need from each of the product teams is how to kick off the product tests so I plugin them into ESTF build script.   Let me know if you'd like to discuss to see if this fits your needs or if you have any questions.  Thanks !
