### ISSUE TITLE
Logstash failing to shut down

### ISSUE THREAD

**Issue by cachedout** [elastic/elastic-stack-testing#395]
It appears that monitoring parity tests against Logstash [are failing](https://internal-ci.elastic.co/job/elastic+estf-monitoring-snapshots+master+multijob-logstash/15/consoleFull) because the Logstash process is not respecting a SIGTERM.

While this may be somewhat similar [to issues diagnosed earlier in the summer](https://github.com/elastic/elastic-stack-testing/issues/302) by @ycombinator, I believe this is actually different because no amount of time will pass before Logstash will shut down after a SIGTERM in my testing.

I thought we might be able to get around this by adding a [`--pipeline.unsafe_shutdown`](https://www.elastic.co/guide/en/logstash/current/shutdown.html#_what_happens_during_a_controlled_shutdown) to the Logstash configuration but after testing it locally, it appears to have no effect. Even after multiple attempts of trying to kill Logstash by hand using `kill -SIGTERM`, the process remains running.

I believe that this is a bug in Logstash and I have [filed an issue in that repo to track it](https://github.com/elastic/logstash/issues/11253).

However, we could potentially work around this on the testing side [by changing from a SIGTERM to a SIGKILL](https://github.com/elastic/elastic-stack-testing/blob/master/ansible/roles/logstash/tasks/linux/logstash_shutdown_tar.yml#L9). While not ideal, this should at least get the tests working again.

What do you think about that option, @liza-mae ?

**Comment by liza-mae** [comment]
@cachedout I am okay if you want to put a workaround until the issue you filed in logstash is resolved, just put a comment linking to your issue in the code, we can change it back once fixed.
