### ISSUE TITLE
Make CI script for Monitoring parity tests

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-stack-testing#40]
Some time ago we started writing automated tests for ensuring parity between Elasticsearch-indexed and Metricbeat-indexed Monitoring documents. The playbooks, etc. for these tests live here: https://github.com/elastic/elastic-stack-testing/tree/master/playbooks/monitoring.

We'd like to run these tests in Jenkins, whenever a new release manager job runs.

This issue is to write the necessary script that Jenkins can call to trigger these tests.

**Comment by liza-mae** [comment]
ESTF Monitoring jobs are in Jenkins now - thanks for the very speedy review/merge @itsmed !
