### ISSUE TITLE
Run Stack Monitoring parity tests with Basic license too

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-stack-testing#443]
Currently, the Stack Monitoring parity tests use a trial license. This is necessary to collect monitoring stats for certain stack features like CCR. 

However, there are a few differences in the collected monitoring data (e.g. the `license` field in `type: cluster_stats` documents in `.monitoring-es-*`) when a Basic license is in use on the monitored cluster instead of a Trial license.  To account for such differences, it would be nice if we could run the Stack Monitoring tests with a Basic license in addition to running them with a Trial license.

**Comment by ycombinator** [comment]
Pinging @elastic/stack-monitoring.

**Comment by cachedout** [comment]
+1 great idea. I can take this on unless you were planning to.

**Comment by ycombinator** [comment]
> I can take this on unless you were planning to.

Go for it, @cachedout!

**Comment by liza-mae** [comment]
Closing these tests will be removed: https://github.com/elastic/elastic-stack-testing/issues/1153
