### ISSUE TITLE
Cannot build environment in Mac

### ISSUE THREAD

**Issue by mdelapenya** [elastic/elastic-stack-testing#585]
I'm trying to install the build dependencies to run these tests, but the process fails at the very beginning. These are my steps

1. I downgraded local python (3.7) using brew
1. Run `brew unlink python` (later on, with `brew link --overwrite python && brew switch python 3.7.6_1` it's possible to bring back python 3.7)
1. Run `brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb`
1. As described in https://github.com/elastic/elastic-stack-testing#quick-start, edited buildenv.sh
    - export ES_BUILD_URL=artifacts.elastic.co/7.7.0
    - export AIT_ANSIBLE_PLAYBOOK=install_xpack
1. Run `./buildenv.sh`

This last step failed with:
```
[2020-05-27 16:52:59] [INFO] requirements.txt 
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting ansible==2.8.8 (from -r requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/ansible/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/ansible/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/ansible/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/ansible/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/ansible/
  Could not fetch URL https://pypi.python.org/simple/ansible/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/ansible/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)) - skipping
  Could not find a version that satisfies the requirement ansible==2.8.8 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for ansible==2.8.8 (from -r requirements.txt (line 1))
[2020-05-27 16:53:07] [INFO] List installed python packages 
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
pip (9.0.3)
setuptools (39.0.1)
[2020-05-27 16:53:08] [INFO] Run script to build ansible variables from env 
Traceback (most recent call last):
  File "/Users/mdelapenya/sourcecode/src/github.com/elastic/elastic-stack-testing/scripts/python/ansible_es_build_vars.py", line 8, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
[2020-05-27 16:53:08] [ERROR] FAILED! Did not create ansible build variables!
```

**Comment by ycombinator** [comment]
@liza-mae Could you advise on the python errors please?

@mdelapenya the README you want to follow for the stack monitoring parity tests is this one (not the top-level one in this repo): https://github.com/elastic/elastic-stack-testing/tree/master/playbooks/monitoring#running-the-tests. I suspect you'd still run into the same Python errors, though, so I'm hoping @liza-mae can help with that.

**Comment by liza-mae** [comment]
Sure @ycombinator  @mdelapenya I run on Mac OS X and do not have this problem.  

No need to downgrade to python 3.6 as it works on python 3.7, it just does not work on python 3.5 which is why at that time I put python3.6 in the scripts, as some Linux system map python3 to python3.5, butI can upgrade this now.    

- Ensure vagrant and virtualbox are installed.  I am using the latest and they worked fine.
- Delete your ait_workspace. 
- For now to use python3.7 you can just edit the below file to point to your python install.  I will make an enhancement to make this available via env. 

https://github.com/elastic/elastic-stack-testing/blob/925b92ae521bcff6f0671b02f73a73b7297fe53d/scripts/shell/lib/build_funcs.sh#L174

That should be all you need, ping me if you have questions or can not get it to work.

**Comment by liza-mae** [comment]
I linked the file to python3 instead of python3.6 so you can also pull latest if that works better no need to edit the file.

**Comment by mdelapenya** [comment]
What is the value for this variable?
```
export ES_BUILD_URL=artifacts.elastic.co/7.7.0
```
I get:
```Invalid URL: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.7.0.tar.gz
Status code: 404
[2020-05-27 17:58:37] [ERROR] Invalid ansible playbook! 
```

**Comment by liza-mae** [comment]
The error is referring to your Ansible playbook, the build url looks fine.  

What is set for AIT_ANSIBLE_PLAYBOOK ?

**Comment by mdelapenya** [comment]
I updated above comment, as it seems the URL is not found.

The variable you mention takes this value:
```
export AIT_ANSIBLE_PLAYBOOK=install_xpack
```

**Comment by liza-mae** [comment]
I don't believe there is a playbook in that location, which is why you are getting this error. In the playbook directory you need to specify which playbook you want.  For example get_started/install_xpack.

**Comment by liza-mae** [comment]
The 404 URL error is not related and is okay to see that.

**Comment by ycombinator** [comment]
@mdelapenya I'm following the steps I linked to earlier and not getting any issues (https://github.com/elastic/elastic-stack-testing/tree/master/playbooks/monitoring#running-the-tests). In step 3 of those instructions, there's an example of setting the `ES_BUILD_URL`.

**Comment by mdelapenya** [comment]
I followed instructions in here for the values in the shell script: https://github.com/elastic/elastic-stack-testing#quick-start

**Comment by liza-mae** [comment]
For stack monitoring please follow @ycombinator README they maintain those.  I have not updated the quick start at the higher level -  as these mainly just run in CI lately.

**Comment by ycombinator** [comment]
As I said in my last two comments, please follow the instructions at https://github.com/elastic/elastic-stack-testing/tree/master/playbooks/monitoring#running-the-tests, **not in any other READMEs**

**Comment by mdelapenya** [comment]
I think we can close this, as the `python3.6 > python3` change did the thing.

Thanks!

![image](https://media.giphy.com/media/AvMJCeu1EMmhG/giphy.gif)
